### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zejun-chen** [intel/xpumanager#25]
Hi,

I want to build this tool, while it occurs some issue as below.
I use CMake 3.25 and run "sh build.sh" in the repo home path.
![image](https://user-images.githubusercontent.com/74231238/211238942-78773b0a-2e6a-470a-bd29-3c312eec4514.png)

Could someone help take a look ?
The using commit is: https://github.com/intel/xpumanager/commit/04ebef93553e85a3410b6e499388776b7e3642bc

Thank you.

**Comment by eero-t** [comment]
Which of the build directions you're following: https://github.com/intel/xpumanager/blob/master/BUILDING.md ?

Or are you building XPUM in some other way?   As the build output states, you're missing necessary dependencies.

PS. If you're doing this build on Ubuntu, and need also the Python exporter (providing REST API + Prometheus metrics) in addition to "xpumd" daemon and CLI tools, you should avoid Ubuntu 22.04 Python gRPC module due to: https://bugs.launchpad.net/ubuntu/+source/grpc/+bug/1971114

**Comment by zejun-chen** [comment]
Hi,
I use Ubuntu 20.04. Does that mean i need to use the following method to install xpumanager, right ?
![image](https://user-images.githubusercontent.com/74231238/211464214-b5bd4da2-0e2f-4fca-a79d-27f3e26a7b7b.png)

**Comment by eero-t** [comment]
> Hi, I use Ubuntu 20.04. Does that mean i need to use the following method to install xpumanager, right ?

 (I'm not XPUM developer)

If you're not following method documented by XPUM team  (= using process with builder container & building several of the deps from sources), you need to know how to debug & fix the issues you encounter yourself, and have time to do it.

I've been able to build XPUM directly using existing Ubuntu packages, instead of using methods documented by XPUM team, but it's a bit involved. I needed following Ubuntu packages for XPUM: dmidecode intel-metrics-discovery intel-metrics-library libmfx-tools intel-gsc libnl-genl-3-200 libgrpc++1 libexpat1 libjs-jquery mime-support automake libtool build-essential dpkg-dev cmake git gcc g++ libdrm-dev libssl-dev liblua5.2-0 pkg-config intel-metrics-discovery-dev intel-gsc-dev level-zero-dev libnl-genl-3-dev libprotobuf-dev libgrpc++-dev protobuf-compiler-grpc python3-dev python3-grpc-tools python3-grpcio python3-protobuf python3-requests python3-flask-httpauth python3-setuptools python3-certifi python3-click python3-colorama python3-idna python3-six python3-werkzeug python3-pkg-resources

Python packages are needed only for the Python exporter, and driver packages in that list come from Intel package repository, see: https://dgpu-docs.intel.com/installation-guides/index.html

**Comment by zejun-chen** [comment]
Thank you for your help @eero-t 
I find here is the link for the built deb package when the project is released. That could help us to quickly install the XPUManager. I will try it. If it doesn't work for me, i will try your method to build.
https://github.com/intel/xpumanager/releases

**Comment by testdig** [comment]
Hi @zejun-chen, does the pre-built deb package work well? If so, we may close this issue.

**Comment by zejun-chen** [comment]
@testdig It works well. We can close the issue. Thank you.
