### ISSUE TITLE
Intel Arc?

### ISSUE THREAD

**Issue by fredlarochelle** [intel/xpumanager#26]
Any plan on adding support for Intel Arc GPUs? Or any CLI to configure Arc GPUs on Linux?

**Comment by eero-t** [comment]
Current XPU manager releases should support Arc just fine, as long as you have installed a kernel that supports it. Do you have some specific issue?

(DockerHub seems to have only older v.1.0.0 release though, which is bug https://github.com/intel/xpumanager/issues/17.)

**Comment by fredlarochelle** [comment]
Perfect! I will try it over the weekend! Will get back to you if I encounter any problems.

No specific issues, I was just looking around and finding no options to control an Arc GPU on Linux. If it works fine, you should add it to the readme (even if it is with an warning about being experimental).

Thanks!

**Comment by fredlarochelle** [comment]
XPU Manager works _mostly_ fine on my Intel Arc A770.

Here are some of the problem I encountered from my quick testing:
1. There seems to be a problem with getting the Memory Temperature. Different commands like `./xpumcli health -l` outputs `Status: Unknown`. Something similar when using the command `./xpumcli stats -d 0`, `GPU Memory Temperature` and `GPU Memory Bandwith (%)` outputs empty values.
2. When using the command `./xpumcli config -d 0`, the GPU Power Limit Valid Range outputs the following `Valid Range: 1 to 0`. It's missing the upper value of the range.
3. On the subject of power, when using the command `./xpumcli health -l`, I get  that the default `Throttle Threshold` for GPU Power is 300 watts, which seem way to high to be the default value.

Apart from that, it seems to be working fine!

**Comment by eero-t** [comment]
> Here are some of the problem I encountered from my quick testing:

What metrics are supported, depends on the underlying HW, its FW, and kernel + user-space drivers.     All metrics supported by XPU Manager, are not provided by all HW, or their driver stacks.

(For example, Arc does not have fabric ports, so there are no fabric port metrics, and integrated GPUs do not have even their own memory, so those do not provide any memory metrics.)

To determine whether the missing metric is due to XPU Manager (or user-space drivers included to its container), you need to use the tester included with the level-zero backend code.

If that tester reports the metrics, but XPU Manager does not, only then it is a XPU manager specific problem.  Otherwise it's an issue in the lower layers.

First install the driver repo for latest Arc drivers, using these instructions: https://dgpu-docs.intel.com/installation-guides/index.html

Then build the tester:
```
$ TESTER=zello_sysman
$ sudo apt install wget g++ level-zero-dev intel-level-zero-gpu intel-opencl-icd
$ wget https://raw.githubusercontent.com/intel/compute-runtime/master/level_zero/tools/test/black_box_tests/$TESTER.cpp
$ g++ -O2 -Wall -o $TESTER $TESTER.cpp -lze_loader -locloc
$ sudo install -s -m 755 $TESTER /usr/local/bin/$TESTER
```

And check whether it reports e.g. temperature:
```
$ zello_sysman --temperature
```

**Comment by eero-t** [comment]
PS. Another monitoring option for those who are comfortable in building their own software, is Sysman plugin for the collectd v6.0 branch: https://github.com/collectd/collectd/pull/3968

(Sysman plugin does not have official support / validation like XPUM has, nor provide other features besides metric monitoring, whereas XPU Manager provides also tooling for large number of GPU management features like FW upgrades, SR-IOV setup etc.)
