### ISSUE TITLE
"xpumcli dump" doesn't report all stats unless you use the --rawdata option

### ISSUE THREAD

**Issue by jmechalas** [intel/xpumanager#7]
If I run `xpumcli dump` and start a raw data dump like this:

```
xpumcli dump --rawdata --start -d 0 -t 0 -m 0,1,2,3,4,5
```

It writes the requested metrics to the dump file as expected:

```
Timestamp, DeviceId, TileId, GPU Utilization (%), GPU Power (W), GPU Frequency (MHz), GPU Core Temperature (Celsius Degree), GPU Memory Temperature (Celsius Degree), GPU Memory Utilization (%)
2022-07-13T20:41:44.046Z,0,0,0.00,11.00,1400,31.00,32.00,0.00
2022-07-13T20:41:44.546Z,0,0,0.00,11.00,1400,31.00,32.00,0.00
2022-07-13T20:41:45.046Z,0,0,0.00,11.00,1400,30.00,32.00,0.00
2022-07-13T20:41:45.546Z,0,0,0.00,11.00,1400,31.00,32.00,0.00
```

If I run `xpumcli dump` on the command-line to retrieve stats on-demand, most fields are blank:

```
# ./xpumcli dump -d 0 -m 0,1,2,3,4,5 -n 4
Timestamp, DeviceId, GPU Utilization (%), GPU Power (W), GPU Frequency (MHz), GPU Core Temperature (Celsius Degree), GPU Memory Temperature (Celsius Degree), GPU Memory Utilization (%)
2022-07-13T21:04:48.000Z,    0,     , 44.60,     ,     ,     ,     
2022-07-13T21:04:49.000Z,    0,     , 44.60,     ,     ,     ,     
2022-07-13T21:04:50.000Z,    0,     , 44.61,     ,     ,     ,     
2022-07-13T21:04:51.000Z,    0,     , 44.62,     ,     ,     ,     
```

This is the CentOS build. Tested both in a CentOS 8.4 container, and on bare metal with Rocky 8.5.

**Comment by whbruce** [comment]
If you only have one tile, don't specify `-t 0`.

**Comment by yupengzh-intel** [comment]
Hi @jmechalas , the difference is caused by "-t" option. XPUM has to handle different device models. Some cards have two or more tiles but some not. And some metrics can be derived from both whole-card level or per-tile level. So XPUM add "-t" option to distinguish the source. 

With XPUM version 1.0 and earlier, when "-t" is not designated, XPUM would dump only whole-card level data, vice versa. In this case, whole-card level only contains Power data, so XPUM only dumps it.

Since version 1.1, when "-t" is not designated, if whole-card level data is absent, XPUM will aggregate tile-level data and show.

**Comment by yupengzh-intel** [comment]
> If you only have one tile, don't specify `-t 0`.

Yes, if you designate tile id on device without a tile/with only one tile, XPUM would dump no data.
