### ISSUE TITLE
Write timestamps with data during dumping

### ISSUE THREAD

**Issue by WardLT** [intel/xpumanager#79]
I'm using `xpu-smi` to track an application which runs for multiple hours. I'd like to get xpu-smi to write a date along with the time for each interval so I don't have to detect the hours switching from 23->0 at midnight.

**Comment by taotod** [comment]
Sound reasonable. We will improve it in the future version.

**Comment by taotod** [comment]
Hi, @WardLT 
Date is supported in dump command since V1.2.36 when the parameter "--date" is specified. 
https://github.com/intel/xpumanager/releases/tag/V1.2.36

An example is below.  I close this issue. 
xpu-smi dump -d 0 -m 0,1,2,3 --date
Timestamp, DeviceId, GPU Utilization (%), GPU Power (W), GPU Frequency (MHz), GPU Core Temperature (Celsius Degree)
2024-05-06T05:47:53.671,    0, 0.00, 42.99,    0, 24.00
2024-05-06T05:47:54.671,    0, 0.00, 43.10,    0, 25.00
2024-05-06T05:47:55.671,    0, 0.00, 43.09,    0, 24.00

**Comment by WardLT** [comment]
Fantastic. Thanks!
